:bug: aws ssm send-command 수정

diff --git a/.github/workflows/dev-batch-deploy.yml b/.github/workflows/dev-batch-deploy.yml
--- a/.github/workflows/dev-batch-deploy.yml
+++ b/.github/workflows/dev-batch-deploy.yml
@@ -117,16 +117,17 @@ jobs:
         run: |
           COMMAND_ID=$(aws ssm send-command \
             --document-name "AWS-RunShellScript" \
-            --targets "Key=InstanceIds,Values=${{ steps.get-instance-id.outputs.instance_id }}" \
-            --parameters 'commands=["${{ env.DEPLOY_COMMAND }}"]' \   
+            --targets Key=InstanceIds,Values=${{ steps.get-instance-id.outputs.instance_id }} \
+            --parameters commands=["${{ env.DEPLOY_COMMAND }}"] \
+            --comment "Deploy new Docker container" \
             --query "Command.CommandId" \
             --output text \
             --region ${{ env.AWS_REGION }})
 
           if [ -z "$COMMAND_ID" ]; then
-            echo "Failed to send command"
-            exit 1
-          fi
+                  echo "Failed to send command"
+                  exit 1
+                fi
 
           echo "SSM Command ID: $COMMAND_ID"
           echo "::set-output name=command_id::$COMMAND_ID"
